[plugins]
centralPublishing = { id = "dev.lukebemish.central-portal-publishing", version.ref = "centralPublishing" }

[versions]
indra = "4.0.0"
gradleErrorprone = "4.3.0"
spotless = "8.1.0"
centralPublishing = "0.1.7"

[libraries]
indra-common = { module = "net.kyori:indra-common", version.ref = "indra" }
indra-crossdoc = { module = "net.kyori:indra-crossdoc", version.ref = "indra" }
centralPublishing = { module = "dev.lukebemish:central-portal-publishing", version.ref = "centralPublishing" }
errorprone-gradle = { module = "net.ltgt.gradle:gradle-errorprone-plugin", version.ref = "gradleErrorprone" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
palantir-baseline = { module = "com.palantir.baseline:gradle-baseline-java", version = "6.52.0" }
revapi = "org.revapi.revapi-gradle-plugin:org.revapi.revapi-gradle-plugin.gradle.plugin:1.8.0"
